name: Heroku Deploy on Push
on:
  push:
    branches:
      - main

jobs:
  HerokuDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - run: npm run db-push
      - name: Run production migrations
        run: npm run prisma-prod
        env:
          DATABASE_URL:  ${{secrets.DATABASE_URL}}
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pet-db-api"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
